In [132]:
import sys
import numpy as np

In [133]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [134]:
a = np.array([1, 2, 3, 4])

In [135]:
b = np.array([0, .5, 1, 1.5, 2])

In [136]:
a[0], a[1]

(1, 2)

In [137]:
a[0:]

array([1, 2, 3, 4])

In [138]:
a[1:3]

array([2, 3])

In [139]:
a[1:-1]

array([2, 3])

##### // To get all odd index

In [140]:
a[::2] 

array([1, 3])

In [141]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [142]:
b[0],b[2],b[-1]

(0.0, 1.0, 2.0)

In [143]:
b[[0, 2, -1]]

array([0., 1., 2.])

# ARRAY TYPES

In [144]:
a

array([1, 2, 3, 4])

In [145]:
a.dtype

dtype('int32')

In [146]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [147]:
b.dtype

dtype('float64')

In [148]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [149]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [150]:
c = np.array(['a', 'b', 'c'])

In [151]:
c.dtype

dtype('<U1')

In [152]:
d = np.array([{'a': 1}, sys])

In [153]:
d.dtype

dtype('O')

# Dimensions and Shapes

In [154]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [155]:
A.shape

(2, 3)

In [156]:
A.ndim

2

In [157]:
A.size

6

In [158]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [159]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [160]:
B.shape

(2, 2, 3)

In [161]:
B.ndim

3

In [162]:
B.size

12

//If the shape isn't consistent, it'll just fall back to regular Python objects:

In [165]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

<class 'ValueError'>: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [166]:
C.dtype

<class 'NameError'>: name 'C' is not defined

In [167]:
C.shape

<class 'NameError'>: name 'C' is not defined

# Indexing and Slicing of Matrices

In [168]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [169]:
A[1]

array([4, 5, 6])

In [170]:
A[1][0]

4

In [171]:
# A[d1, d2, d3, d4]

In [172]:
A[1,0]

4

In [173]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [175]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [176]:
A[:2, 2:]

array([[3],
       [6]])

In [177]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
A[1] = np.array([10, 10, 10])

In [46]:
A[2] = 99

In [47]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary Statistics

In [48]:
a = np.array([1, 2, 3, 4])

In [49]:
a.sum()

10

In [50]:
a.mean()

2.5

In [51]:
a.std()

1.118033988749895

In [52]:
a.var()

1.25

In [53]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [54]:
A.sum()

45

In [55]:
A.mean()

5.0

In [56]:
A.std()

2.581988897471611

In [57]:
A.sum(axis=0)

array([12, 15, 18])

In [58]:
A.sum(axis=1)

array([ 6, 15, 24])

In [59]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [60]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Broadcasting and Vectorized operations

In [61]:
a = np.arange(4)

In [62]:
a

array([0, 1, 2, 3])

In [63]:
a + 10

array([10, 11, 12, 13])

In [64]:
a * 10

array([ 0, 10, 20, 30])

In [65]:
a

array([0, 1, 2, 3])

In [66]:
a +=100

In [67]:
a

array([100, 101, 102, 103])

In [68]:
l = [0, 1, 2, 3]

In [69]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [70]:
a = np.arange(4)

In [71]:
a

array([0, 1, 2, 3])

In [72]:
b = np.array([10, 10, 10, 10])

In [73]:
a + b

array([10, 11, 12, 13])

In [74]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays

##### _(Also called masks)_

In [75]:
a = np.arange(4)

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a[[0, -1]]

array([0, 3])

In [78]:
a[[True, False, False, True]]

array([0, 3])

In [79]:
a >= 2

array([False, False,  True,  True])

In [80]:
a[a >= 2]

array([2, 3])

In [81]:
a.mean()

1.5

In [82]:
a[a > a.mean()]

array([2, 3])

In [83]:
a[~(a > a.mean())]

array([0, 1])

In [84]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [85]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [86]:
A = np.random.randint(100, size=(3, 3))

In [87]:
A

array([[48, 38,  6],
       [19, 59, 55],
       [63, 24, 24]])

In [88]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([48,  6, 59, 63, 24])

In [89]:
A > 30

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False, False]])

In [90]:
A[A > 30]

array([48, 38, 59, 55, 63])

# Linear Algebra

In [91]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [92]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [93]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [94]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [95]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [96]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in Memory

#### Int, floats

In [98]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

<class 'NameError'>: name 'sys' is not defined

In [99]:
# Longs are even larger
sys.getsizeof(10**100)

<class 'NameError'>: name 'sys' is not defined

In [100]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [101]:
np.dtype(float).itemsize

8

# Lists are even larger

In [102]:
# A one-element list
sys.getsizeof([1])

<class 'NameError'>: name 'sys' is not defined

In [103]:
# An array of one element in numpy
np.array([1]).nbytes

4

### And performance is also important

In [104]:
l = list(range(1000))

In [105]:
a = np.arange(1000)

In [106]:
%time np.sum(a ** 2)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 0 ns


332833500

In [107]:
%time sum([x ** 2 for x in l])

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 0 ns


332833500

## Useful Numpy functions

### random

In [108]:
np.random.random(size=2)

array([0.88297603, 0.70184096])

In [109]:
np.random.normal(size=2)

array([ 1.08260601, -0.38922627])

In [110]:
np.random.rand(2, 4)

array([[0.58292721, 0.75043686, 0.95770178, 0.46763076],
       [0.86025223, 0.06233567, 0.61133192, 0.94943949]])

## arange

In [111]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [113]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## reshape

In [114]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [115]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## linspace

In [116]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [117]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [118]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## zeros, ones, empty

In [119]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [120]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [121]:
np.zeros((3, 3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [122]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [123]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [124]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [125]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

## identity and eye

In [126]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [127]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [129]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [131]:
"Hello World"[6]

'W'